/* eslint-disable no-restricted-globals */
/* eslint-disable no-unused-expressions */
/* eslint-disable no-undef */

https://www.w3schools.com/css/css_colors.asp
https://www.w3schools.com/css/css_colors_rgb.asp
https://www.w3schools.com/css/css_colors_hex.asp
https://www.w3schools.com/css/css_colors_hsl.asp
https://www.w3schools.com/css/css_background.asp
https://www.w3schools.com/css/css_background_image.asp
https://www.w3schools.com/css/css_background_repeat.asp
https://www.w3schools.com/css/css_background_attachment.asp
https://www.w3schools.com/css/css_background_shorthand.asp
https://www.w3schools.com/css/css_border.asp
https://www.w3schools.com/css/css_border_width.asp
https://www.w3schools.com/css/css_border_color.asp
https://www.w3schools.com/css/css_border_sides.asp
https://www.w3schools.com/css/css_border_shorthand.asp
https://www.w3schools.com/css/css_border_rounded.asp
https://www.w3schools.com/css/css_margin.asp
https://www.w3schools.com/css/css_margin_collapse.asp
https://www.w3schools.com/css/css_padding.asp
https://www.w3schools.com/css/css_dimension.asp
https://www.w3schools.com/css/css_boxmodel.asp
https://www.w3schools.com/css/css_outline.asp
https://www.w3schools.com/css/css_outline_width.asp
https://www.w3schools.com/css/css_outline_color.asp
https://www.w3schools.com/css/css_outline_shorthand.asp
https://www.w3schools.com/css/css_outline_offset.asp
https://www.w3schools.com/css/css_text.asp
https://www.w3schools.com/css/css_text_align.asp
https://www.w3schools.com/css/css_text_decoration.asp
https://www.w3schools.com/css/css_text_transformation.asp
https://www.w3schools.com/css/css_text_spacing.asp
https://www.w3schools.com/css/css_text_shadow.asp
https://www.w3schools.com/css/css_font.asp
https://www.w3schools.com/css/css_font_style.asp
https://www.w3schools.com/css/css_font_size.asp
https://www.w3schools.com/css/css_font_google.asp
https://www.w3schools.com/css/css_font_shorthand.asp
https://www.w3schools.com/css/css_icons.asp
https://www.w3schools.com/css/css_link.asp
https://www.w3schools.com/css/css_list.asp
https://www.w3schools.com/css/css_table.asp
https://www.w3schools.com/css/css_display_visibility.asp
https://www.w3schools.com/css/css_max-width.asp
https://www.w3schools.com/css/css_positioning.asp
https://www.w3schools.com/css/css_overflow.asp
https://www.w3schools.com/css/css_float.asp
https://www.w3schools.com/css/css_float_clear.asp
https://www.w3schools.com/css/css_float_examples.asp
https://www.w3schools.com/css/css_inline-block.asp
https://www.w3schools.com/css/css_align.asp
https://www.w3schools.com/css/css_combinators.asp
https://www.w3schools.com/css/css_pseudo_classes.asp
https://www.w3schools.com/css/css_pseudo_elements.asp
https://www.w3schools.com/css/css_image_transparency.asp
https://www.w3schools.com/css/css_navbar.asp
https://www.w3schools.com/css/css_navbar_vertical.asp
https://www.w3schools.com/css/css_navbar_horizontal.asp
https://www.w3schools.com/css/css_dropdowns.asp
https://www.w3schools.com/css/css_image_gallery.asp
https://www.w3schools.com/css/css_image_sprites.asp
https://www.w3schools.com/css/css_attribute_selectors.asp
https://www.w3schools.com/css/css_form.asp
https://www.w3schools.com/css/css_counters.asp
https://www.w3schools.com/css/css_website_layout.asp
https://www.w3schools.com/css/css_units.asp
https://www.w3schools.com/css/css_specificity.asp
https://www.w3schools.com/css/css3_borders.asp
https://www.w3schools.com/css/css3_border_images.asp
https://www.w3schools.com/css/css3_backgrounds.asp
https://www.w3schools.com/css/css3_colors.asp
https://www.w3schools.com/css/css3_gradients.asp
https://www.w3schools.com/css/css3_gradients_radial.asp
https://www.w3schools.com/css/css3_shadows.asp
https://www.w3schools.com/css/css3_shadows_box.asp
https://www.w3schools.com/css/css3_text_effects.asp
https://www.w3schools.com/css/css3_fonts.asp
https://www.w3schools.com/css/css3_2dtransforms.asp
https://www.w3schools.com/css/css3_3dtransforms.asp
https://www.w3schools.com/css/css3_transitions.asp
https://www.w3schools.com/css/css3_animations.asp
https://www.w3schools.com/css/css_tooltip.asp
https://www.w3schools.com/css/css3_images.asp
https://www.w3schools.com/css/css3_object-fit.asp
https://www.w3schools.com/css/css3_buttons.asp
https://www.w3schools.com/css/css3_pagination.asp
https://www.w3schools.com/css/css3_multiple_columns.asp
https://www.w3schools.com/css/css3_user_interface.asp
https://www.w3schools.com/css/css3_variables.asp
https://www.w3schools.com/css/css3_box-sizing.asp
https://www.w3schools.com/css/css3_flexbox.asp
https://www.w3schools.com/css/css3_mediaqueries.asp
https://www.w3schools.com/css/css3_mediaqueries_ex.asp
https://www.w3schools.com/css/css_rwd_intro.asp
https://www.w3schools.com/css/css_rwd_viewport.asp
https://www.w3schools.com/css/css_rwd_grid.asp
https://www.w3schools.com/css/css_rwd_mediaqueries.asp
https://www.w3schools.com/css/css_rwd_images.asp
https://www.w3schools.com/css/css_rwd_videos.asp
https://www.w3schools.com/css/css_rwd_frameworks.asp
https://www.w3schools.com/css/css_rwd_templates.asp
https://www.w3schools.com/css/css_grid.asp
https://www.w3schools.com/css/css_grid_container.asp
https://www.w3schools.com/css/css_grid_item.asp
https://www.w3schools.com/css/css_templates.asp
https://www.w3schools.com/css/css_examples.asp
https://www.w3schools.com/css/css_exam.asp
https://www.w3schools.com/cssref/css_functions.asp
https://www.w3schools.com/cssref/css_ref_aural.asp
https://www.w3schools.com/cssref/css_websafe_fonts.asp
https://www.w3schools.com/cssref/css_animatable.asp
https://www.w3schools.com/cssref/css_units.asp
https://www.w3schools.com/cssref/css_pxtoemconversion.asp
https://www.w3schools.com/cssref/css_colors.asp
https://www.w3schools.com/cssref/css_colors_legal.asp
https://www.w3schools.com/cssref/css_default_values.asp
https://www.w3schools.com/css/tryit.asp?filename=trycss_border-style
https://www.w3schools.com/colors/colors_picker.asp
https://www.w3schools.com/howto/howto_js_tabs.asp
https://www.w3schools.com/howto/howto_css_dropdown.asp
https://www.w3schools.com/howto/howto_js_accordion.asp
https://www.w3schools.com/howto/howto_js_sidenav.asp
https://www.w3schools.com/howto/howto_js_topnav.asp
https://www.w3schools.com/howto/howto_css_modals.asp
https://www.w3schools.com/howto/howto_js_progressbar.asp
https://www.w3schools.com/howto/howto_css_parallax.asp
https://www.w3schools.com/howto/howto_css_login_form.asp
https://www.w3schools.com/howto/howto_html_include.asp
https://www.w3schools.com/howto/howto_google_maps.asp
https://www.w3schools.com/howto/howto_js_rangeslider.asp
https://www.w3schools.com/howto/howto_css_tooltip.asp
https://www.w3schools.com/howto/howto_js_slideshow.asp
https://www.w3schools.com/howto/howto_js_filter_lists.asp
https://www.w3schools.com/howto/howto_js_sort_list.asp
http://www.facebook.com/sharer.php?u=https://www.w3schools.com/css/css_border.asp
https://twitter.com/home?status=Currently%20reading%20https://www.w3schools.com/css/css_border.asp
https://www.w3schools.com/cert/cert_html.asp
https://www.w3schools.com/about/default.asp
https://www.w3schools.com/colors/colors_names.asp
https://www.w3schools.com/html/html_examples.asp
https://www.w3schools.com/js/js_examples.asp
https://www.w3schools.com/sql/sql_examples.asp
https://www.w3schools.com/python/python_examples.asp
https://www.w3schools.com/w3css/w3css_examples.asp
https://www.w3schools.com/bootstrap/bootstrap_examples.asp
https://www.w3schools.com/php/php_examples.asp
https://www.w3schools.com/jquery/jquery_examples.asp
https://www.w3schools.com/java/java_examples.asp
https://www.w3schools.com/xml/xml_examples.asp
https://www.w3schools.com/about/about_copyright.asp
https://www.w3schools.com/about/about_privacy.asp